In [78]:
import numpy as np
import pandas as pd


# Question 1
* What's the version of NumPy that you installed?
* You can get the version information using the __version__ field:

In [79]:
np.__version__


'1.19.5'

# Question 2

What's the version of Pandas?

In [80]:
pd.__version__

'1.3.2'

What's the version of Pandas?

In [81]:
df1 = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
)
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
)

# Question 3

In [82]:
col_names = df.columns.tolist()
print("Column names:")
print(col_names,'\n')

print('Data dimensions:',df.shape,'\n')

print("Sample data:")
df.head(3)

Column names:
['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP', 'Engine Cylinders', 'Transmission Type', 'Driven_Wheels', 'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style', 'highway MPG', 'city mpg', 'Popularity', 'MSRP'] 

Data dimensions: (11914, 16) 

Sample data:


,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350


In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Make               11914 non-null  object 
 1   Model              11914 non-null  object 
 2   Year               11914 non-null  int64  
 3   Engine Fuel Type   11911 non-null  object 
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object 
 7   Driven_Wheels      11914 non-null  object 
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object 
 10  Vehicle Size       11914 non-null  object 
 11  Vehicle Style      11914 non-null  object 
 12  highway MPG        11914 non-null  int64  
 13  city mpg           11914 non-null  int64  
 14  Popularity         11914 non-null  int64  
 15  MSRP               11914 non-null  int64  
dtypes: float64(3), int64(5

In [84]:
df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [85]:
print ("Avarage price of BMW" )
print ( df[df["Make"] =="BMW"].MSRP.mean())

Avarage price of BMW
61546.76347305389


# Question 4

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). 
How many of them have missing values for Engine HP?

In [86]:
df_1 = df[df["Year"].astype(str).astype(int) >= 2015]

In [87]:
print("missing values for Engine HP")
df_1["Engine HP"].isnull().sum()

missing values for Engine HP


51

# Question 5

* Calculate the average "Engine HP" in the dataset
* Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
* Now, calcualte the average of "Engine HP" again.
* Has it changed?
* Round both means before answering this questions. You can use the round function for that:

In [88]:
mean_hp_before = df["Engine HP"].mean()
print("mean_hp_before",mean_hp_before)

mean_hp_before 249.38607007176023


In [89]:
df["Engine HP"].fillna(mean_hp_before)

0        335.0
1        300.0
2        300.0
3        230.0
4        230.0
         ...  
11909    300.0
11910    300.0
11911    300.0
11912    300.0
11913    221.0
Name: Engine HP, Length: 11914, dtype: float64

In [90]:
mean_hp_after = df["Engine HP"].mean()
print("mean_hp_after" , mean_hp_after)

mean_hp_after 249.38607007176023


In [91]:
print(round(mean_hp_before))
print(round(mean_hp_after))

249
249


# Question 6
* Select all the "Rolls-Royce" cars from the dataset.
* Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
* Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Invert XTX.
* What's the sum of all the elements of the result?

In [104]:
df2 = df1[df1["Make"] =="Rolls-Royce"]
df2.head(3)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
2921,Rolls-Royce,Corniche,2001,premium unleaded (required),325.0,8.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Luxury",Large,Convertible,15,10,86,359990
3505,Rolls-Royce,Dawn,2016,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Large,Convertible,19,12,86,335000
5275,Rolls-Royce,Ghost Series II,2015,premium unleaded (required),563.0,12.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury,Performance",Large,Sedan,21,13,86,286750


In [114]:
df2 = df2[["Engine HP", "Engine Cylinders", "highway MPG"]]
df2 = df2.drop_duplicates() 
df2.head(10)

,Engine HP,Engine Cylinders,highway MPG
2921,325.0,8.0,15
3505,563.0,12.0,19
5275,563.0,12.0,21
5279,563.0,12.0,20
7443,322.0,12.0,15
7553,453.0,12.0,19
11448,624.0,12.0,21


In [128]:
X = np.array(df2)
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [130]:
T = X.transpose()
T

array([[325., 563., 563., 563., 322., 453., 624.],
       [  8.,  12.,  12.,  12.,  12.,  12.,  12.],
       [ 15.,  19.,  21.,  20.,  15.,  19.,  21.]])

In [140]:
 

XTX = T.dot(X) 
XTX


array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [141]:
inverse = np.linalg.inv(XTX)

In [136]:
inverse

array([[-1.17692099e+08, -1.52663979e+10, -2.18643478e+10,
         9.87667349e+09,  3.92546916e+08,  9.09157436e+09,
         1.78484123e+10],
       [ 8.93682480e+08, -6.04247044e+09, -3.20165591e+10,
         2.84987651e+08, -5.39140092e+09,  2.25210206e+10,
         2.00486338e+10],
       [-7.72687444e+09, -8.71098714e+09,  2.13199250e+10,
        -7.83814164e+09,  5.15149355e+09, -6.68785992e+09,
         1.91681981e+09],
       [-4.27931933e+09,  3.06576812e+09,  7.52506722e+09,
         1.49603739e+10, -4.73949961e+09,  1.53288406e+09,
        -1.94917142e+10],
       [-2.30129737e+09, -1.24944503e+10,  3.69154214e+09,
         4.11008733e+09,  5.17866104e+09, -6.24722516e+09,
         7.29558321e+09],
       [ 8.09102325e+09,  3.43597384e+10,  6.24722516e+09,
        -1.51570999e+10, -7.57855893e+09,  0.00000000e+00,
        -2.32653202e+10],
       [ 5.40124681e+09, -0.00000000e+00,  7.80903145e+09,
        -2.94465640e+09,  7.11760693e+09, -1.71798692e+10,
         1.5970560

In [142]:
np.sum(inverse)

0.032212320677486125

# Questions 7
* Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the first element of w?.

In [139]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [143]:
result = inverse.dot(T)

In [144]:
W = result.dot(y)

In [145]:
W

array([ 0.19989598, 31.02612262, 31.65378877])